### ISSUE TITLE
[Bug report] Photo manager image provider import doesn't work

### ISSUE THREAD

**Issue by Tomushh97** [fluttercandies/flutter_photo_manager_plugins#1]
### Version

3.0.0

### Platforms

dart

### Device Model

Pixel

### flutter info

```sh
[√] Flutter (Channel stable, 3.16.0, on Microsoft Windows [Version 10.0.22621.2715], locale pl-PL)
    • Flutter version 3.16.0 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision db7ef5bf9f (9 days ago), 2023-11-15 11:25:44 -0800
    • Engine revision 74d16627b9
    • Dart version 3.2.0
    • DevTools version 2.28.2
```

### How to reproduce?

Hey, anyone knows what to do when I added this image provider to use AssetEntityImageProvider and tried to add import for that as it is said in docs about migrating (https://github.com/fluttercandies/flutter_photo_manager/blob/main/MIGRATION_GUIDE.md#assetentityimage-and-assetentityimageprovider) and nothing is recognized? Is it a typo? Should it be any other import? I have no clue

**Comment by AlexV525** [comment]
Try restart you editor.
